### ISSUE TITLE
Django 4.2 and Wagtail 5.2 compatibility

### ISSUE THREAD

**Issue by danhayden** [borisbrue/wagtail-tenants#10]
Hi, I'm interested in trying out wagtail-tenants on a new project I'm working on which is using Django 4.2 and Wagtail 5.2.

I realised that the current version of wagtail-tenants (0.2.0) is incompatible with Django 4.2 due to the dependency on django-dbbackup=^3.3.0 which uses features no longer available in Django. I noticed however that version 0.3.0 is currently in development which addresses this. I wanted to ask if you have an estimated date when version 0.3.0 will likely be released?

On a related note when browsing the code for 0.3.0 (https://github.com/borisbrue/wagtail-tenants/compare/main...feature/clientFeatures) I noticed a typo in several places.. `TEANTS` has been used several times where I assume it should be `TENANTS`

**Comment by borisbrue** [comment]
Hi Dan, thank you very much for the advice. I have the `clientFeatures` branch already running in one project. But because of some breaking changes and no time for the documentation, it's not completely ready for the master. 

Anyway, I updated the typo. Feel free to test it with that branch. If you need some info about add in the branch in your project with poetry, just let me know.

**Comment by danhayden** [comment]
Thanks for the quick reply Boris. I managed to install the `clientFeatures` branch using poetry by adding the below line to the `[tool.poetry.dependencies]` section in pyproject.toml and running `poetry update`

```
wagtail-tenants = { git = "https://github.com/borisbrue/wagtail-tenants.git", rev = "feature/clientFeatures" }
```

I'm not sure if that's the ideal way of adding a GitHub dependency to poetry but it appears to have worked, please advise if there is a better why.

---

On to configuration I'm not clear on how to determine which apps should be location in `SHARED_APPS` and which in `TENANT_APPS`, any advice or guidance would be welcomed. My first few attempts resulted in errors when running `./manage.py migrate_schemas --shared`. So for now I am using what you suggested in https://github.com/borisbrue/wagtail-tenants/issues/6#issuecomment-1472113801 this enabled me to run `./manage.py migrate_schemas --shared` without errors.

On to the next step I stumbled in to another issue when running `./manage.py create_tenant`

I entered the following info

```
schema name: public
name: localhost
paid until ('YYYY-MM-DD'): 2024-06-01
on trial ('True' or 'False'): False
plan: 1
```

not entirely sure what on trial or plan relate to just yet, and got the following error and I'm not sure how to proceed

```
insert or update on table "customers_client" violates foreign key constraint "customers_client_plan_id_69976bcb_fk_customers"
DETAIL:  Key (plan_id)=(1) is not present in table "customers_clientfeaturegroup".
```

Please let me know if there is something I have missed or any further docs I can read.

Thank you for your help, I look forward to  exploring wagtail-tenants further.

**Comment by danhayden** [comment]
### update 

- Leaving `plan` blank allowed me to proceed to the next step and complete the configuration process
- Also I had to add "wagtail_modeladmin"  to `SHARED_APPS` (once added to poetry) to access the admin pages due to missing templates
