### ISSUE TITLE
the default schema has no domains associated with

### ISSUE THREAD

**Issue by hazho** [borisbrue/wagtail-tenants#2]
currently, if you follow the documentations tep by step, the public schema has no doamin associated with, therefore it is not visitable in the development stage (localhost), it would be good if we add a new management command for that

**Comment by borisbrue** [comment]
Hi @hazho the default domain process is within the create_tenant command. 
It should ask you for the default domain and that should be localhost. But you are right. The docs are "patchy" at that point.
